# Site settings
title: Emoji Reviews
header-img: img/home-bg.jpg
email: your-email@yourdomain.com
copyright_name: Emoji Reviews
description: "A blog reviewing food, movies, games, and more written soley with emoji"
baseurl: "/emojireviews"
url: "https://philipsdyoo.github.io"
#twitter_username: SBootstrap
github_username:  philipsdyoo
#facebook_username:  IronSummitMedia
email_username:  your-email@yourdomain.com

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
future: true
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
